SELECTION_GOODS, SELECTION_REGION, SELECTION_PAYMENT = map(str, range(1, 4))
SUBMIT_PAYMENT, REJECT_ORDER, ORDER_MENU = map(str, range(4, 7))
SELECTION_FIELDS, INPUT, CH_INDEX, CH_NAME = map(str, range(7, 11))
CH_REGION, CH_PHOTO, CH_PRICE, CH_SUBMIT = map(str, range(11, 15))
CHANGE_FIELD = map(str, range(15, 16))
END = -1

KUNA_API = "https://api.kuna.io"
KUNA_PUBLIC = "KUNA_API_PUBLIC"
KUNA_PRIVATE = "KUNA_API_PRIVATE"
KUNA_INSTRUCTION = "https://telegra.ph/INSTRUCTION"
BOT_TOKEN = "BOT_TOKEN"
ADMIN_IDS = (1, )
IMAGES_PATH = "images"
